apiVersion: v1
kind: ReplicationController
metadata:
  name: stress
spec:
  replicas: 1
  selector:
    app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: hello
        image: benjones/es-test-client

        ports:
          - name: stress
            containerPort: 80
        resources:
          limits:
            cpu: 0.5
            memory: "100Mi"
