apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-stress
spec:
  replicas: 1
  selector:
    app: elasticsearch-stress
  template:
    metadata:
      labels:
        app: elasticsearch-stress
    spec:
      containers:
      - name: hello
        image: benjones/es-test
        env:
            - name: GRPC_PORT
              value: "9090"
            - name: ELASTICSEARCH_URI
              value: "http://elasticsearch:9200"
            - name: ELASTICSEARCH_DEFAULT_INDEX
              value: "stress"
            - name: ELASTICSEARCH_DEFAULT_TYPE
              value: "stress"

        ports:
          - name: grpc
            containerPort: 9090
        resources:
          limits:
            cpu: 0.5
            memory: "100Mi"
